const products = [
    // === MEN'S CLOTHING ===
    {
      id: 1,
      name: "Men's Classic T‑Shirt",
      category: "men",
      type: "T-Shirt",
      price: 19.99,
      colors: ["white", "black", "red"],
      description: "A comfortable cotton classic tee.",
      image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dCUyMHNoaXJ0fGVufDB8fDB8fHww",
      inStock: true,
    },
    {
      id: 2,
      name: "Men's Slim Fit Jeans",
      category: "men",
      type: "Jeans",
      price: 39.99,
      colors: ["blue", "black"],
      description: "Stylish slim-fit denim jeans.",
      image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
      inStock: true,
    },
    {
      id: 3,
      name: "Men's Hoodie",
      category: "men",
      type: "Hoodie",
      price: 34.99,
      colors: ["gray", "navy", "olive"],
      description: "Soft fleece pullover hoodie.",
      image: "https://plus.unsplash.com/premium_photo-1689327920663-406abecf9805?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTd8fG1lbiUyMGhvb2RpZXN8ZW58MHx8MHx8fDA%3D",
      inStock: true,
    },
     
    // === WOMEN'S CLOTHING ===
    {
      id: 21,
      name: "Women's Floral Dress",
      category: "women",
      type: "Dress",
      price: 34.99,
      colors: ["pink", "white", "yellow"],
      description: "Floral-summer maxi dress.",
      image: "https://media.istockphoto.com/id/1331281439/photo/cheerful-young-woman-in-white-t-shirt.webp?a=1&b=1&s=612x612&w=0&k=20&c=EKiXgQuDCdaBO7ny2RO59KjNqtn1R3Kculk1dU_S7yA=",
      inStock: true,
    },
    {
      id: 22,
      name: "Women's Skinny Jeans",
      category: "women",
      type: "Jeans",
      price: 39.99,
      colors: ["blue", "black"],
      description: "High‑rise skinny jeans.",
      image: "https://media.istockphoto.com/id/2177231592/photo/smiling-asian-woman-posing-with-crossed-arms-looking-at-camera-on-blue-background.webp?a=1&b=1&s=612x612&w=0&k=20&c=eBCGJOnTaXbLSis9B_P1JMA7DSKOVDWkICtpaF3wimk=",
      inStock: true,
    },
    {
      id: 23,
      name: "Women's Crop Top",
      category: "women",
      type: "Top",
      price: 19.99,
      colors: ["white", "black", "red"],
      description: "Stylish cotton crop top.",
      image: "https://images.unsplash.com/photo-1631467697445-6c35d744187c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8d29tZW4lMjB0b3BzfGVufDB8fDB8fHww",
      inStock: true,
    },
    {
      id: 24,
      name: "Women's Blazer",
      category: "women",
      type: "Blazer",
      price: 49.99,
      colors: ["black", "navy", "gray"],
      description: "Single‑button formal blazer.",
      image: "https://images.unsplash.com/photo-1600275669177-176b3c586d22?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHdvbWVuJTIwYmxhemVyc3xlbnwwfHwwfHx8MA%3D%3D",
      inStock: true,
    },
    {
        id: 1,
        name: "Men's Classic T‑Shirt",
        category: "men",
        type: "T-Shirt",
        price: 19.99,
        colors: ["white", "black", "red"],
        description: "A comfortable cotton classic tee.",
        image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dCUyMHNoaXJ0fGVufDB8fDB8fHww",
        inStock: true,
      },
      {
        id: 2,
        name: "Men's Slim Fit Jeans",
        category: "men",
        type: "Jeans",
        price: 39.99,
        colors: ["blue", "black"],
        description: "Stylish slim-fit denim jeans.",
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        inStock: true,
      },
      {
        id: 3,
        name: "Men's Hoodie",
        category: "men",
        type: "Hoodie",
        price: 34.99,
        colors: ["gray", "navy", "olive"],
        description: "Soft fleece pullover hoodie.",
        image: "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHQlMjBzaGlydHxlbnwwfHwwfHx8MA%3D%3D",
        inStock: true,
      },
       
      // === WOMEN'S CLOTHING ===
      {
        id: 21,
        name: "Women's Floral Dress",
        category: "women",
        type: "Dress",
        price: 34.99,
        colors: ["pink", "white", "yellow"],
        description: "Floral-summer maxi dress.",
        image: "https://media.istockphoto.com/id/1331281439/photo/cheerful-young-woman-in-white-t-shirt.webp?a=1&b=1&s=612x612&w=0&k=20&c=EKiXgQuDCdaBO7ny2RO59KjNqtn1R3Kculk1dU_S7yA=",
        inStock: true,
      },
      {
        id: 22,
        name: "Women's Skinny Jeans",
        category: "women",
        type: "Jeans",
        price: 39.99,
        colors: ["blue", "black"],
        description: "High‑rise skinny jeans.",
        image: "https://media.istockphoto.com/id/2177231592/photo/smiling-asian-woman-posing-with-crossed-arms-looking-at-camera-on-blue-background.webp?a=1&b=1&s=612x612&w=0&k=20&c=eBCGJOnTaXbLSis9B_P1JMA7DSKOVDWkICtpaF3wimk=",
        inStock: true,
      },
      {
        id: 23,
        name: "Women's Crop Top",
        category: "women",
        type: "Top",
        price: 19.99,
        colors: ["white", "black", "red"],
        description: "Stylish cotton crop top.",
        image: "https://images.unsplash.com/photo-1631467697445-6c35d744187c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8d29tZW4lMjB0b3BzfGVufDB8fDB8fHww",
        inStock: true,
      },
      {
        id: 24,
        name: "Women's Blazer",
        category: "women",
        type: "Blazer",
        price: 49.99,
        colors: ["black", "navy", "gray"],
        description: "Single‑button formal blazer.",
        image: "https://images.unsplash.com/photo-1600275669177-176b3c586d22?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHdvbWVuJTIwYmxhemVyc3xlbnwwfHwwfHx8MA%3D%3D",
        inStock: true,
      },
      {
        id: 1,
        name: "Men's Classic T‑Shirt",
        category: "men",
        type: "T-Shirt",
        price: 19.99,
        colors: ["white", "black", "red"],
        description: "A comfortable cotton classic tee.",
        image: "https://images.unsplash.com/photo-1523381294911-8d3cead13475?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8dCUyMHNoaXJ0fGVufDB8fDB8fHww",
        inStock: true,
      },
      {
        id: 2,
        name: "Men's Slim Fit Jeans",
        category: "men",
        type: "Jeans",
        price: 39.99,
        colors: ["blue", "black"],
        description: "Stylish slim-fit denim jeans.",
        image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
        inStock: true,
      },
      {
        id: 3,
        name: "Men's Hoodie",
        category: "men",
        type: "Hoodie",
        price: 34.99,
        colors: ["gray", "navy", "olive"],
        description: "Soft fleece pullover hoodie.",
        image: "https://images.unsplash.com/photo-1627225924765-552d49cf47ad?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHQlMjBzaGlydHxlbnwwfHwwfHx8MA%3D%3D",
        inStock: true,
      },
       
      // === WOMEN'S CLOTHING ===
      {
        id: 21,
        name: "Women's Floral Dress",
        category: "women",
        type: "Dress",
        price: 34.99,
        colors: ["pink", "white", "yellow"],
        description: "Floral-summer maxi dress.",
        image: "https://media.istockphoto.com/id/1331281439/photo/cheerful-young-woman-in-white-t-shirt.webp?a=1&b=1&s=612x612&w=0&k=20&c=EKiXgQuDCdaBO7ny2RO59KjNqtn1R3Kculk1dU_S7yA=",
        inStock: true,
      },
      {
        id: 22,
        name: "Women's Skinny Jeans",
        category: "women",
        type: "Jeans",
        price: 39.99,
        colors: ["blue", "black"],
        description: "High‑rise skinny jeans.",
        image: "https://media.istockphoto.com/id/2177231592/photo/smiling-asian-woman-posing-with-crossed-arms-looking-at-camera-on-blue-background.webp?a=1&b=1&s=612x612&w=0&k=20&c=eBCGJOnTaXbLSis9B_P1JMA7DSKOVDWkICtpaF3wimk=",
        inStock: true,
      },
      {
        id: 23,
        name: "Women's Crop Top",
        category: "women",
        type: "Top",
        price: 19.99,
        colors: ["white", "black", "red"],
        description: "Stylish cotton crop top.",
        image: "https://images.unsplash.com/photo-1631467697445-6c35d744187c?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8d29tZW4lMjB0b3BzfGVufDB8fDB8fHww",
        inStock: true,
      },
      {
        id: 24,
        name: "Women's Blazer",
        category: "women",
        type: "Blazer",
        price: 49.99,
        colors: ["black", "navy", "gray"],
        description: "Single‑button formal blazer.",
        image: "https://images.unsplash.com/photo-1600275669177-176b3c586d22?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHdvbWVuJTIwYmxhemVyc3xlbnwwfHwwfHx8MA%3D%3D",
        inStock: true,
      },
    
  ];
  
  export default products;
  